apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapps.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: WebApp
    listKind: WebAppList
    plural: webapps
    singular: webapp
    shortNames:
      - wa
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                app_label:
                  type: string
                template:
                  type: object
                  properties:
                    path:
                      type: string
                    parameters:
                      type: object
                      properties:
                        OPENSHIFT_OAUTHCLIENT_ID:
                          type: string
                        OPENSHIFT_OAUTH_HOST:
                          type: string
                        OPENSHIFT_HOST:
                          type: string
                        INSTALLATION_TYPE:
                          type: string
                        INSTALLED_SERVICES:
                          type: string
                        OPENSHIFT_VERSION:
                          type: string
                        WALKTHROUGH_LOCATIONS:
                          type: string
